# Generated by Django 5.0 on 2024-11-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactFormLog',
        ),
    ]
